# Generated by Django 4.1 on 2022-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
    ]
