# Generated by Django 4.1 on 2023-04-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_social_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=50)),
                ('social_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('link', models.URLField()),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.about')),
            ],
        ),
    ]
